<script setup lang="ts">
type Election = { id: string; name: string; status: string; startsAt: string | null; endsAt: string | null }
type Action = { id: string; type: string; status: string; proposerId: string; approverId: string | null; createdAt: string }
const { request } = useApi(); const elections = ref<Election[]>([]); const electionId = ref(''); const actions = ref<Action[]>([]); const loading = ref(false); const saving = ref(false); const error = ref(''); const notice = ref(''); const pauseReason = ref('')
const current = computed(() => elections.value.find(e => e.id === electionId.value))
const labels: Record<string, string> = { OPEN: 'Buka voting', RECOVER: 'Lanjutkan voting', CLOSE_EARLY: 'Tutup lebih awal', PUBLISH: 'Publikasikan hasil', ARCHIVE: 'Arsipkan' }
async function loadElections() { try { const result = await request<{ elections: Election[] }>('/api/v1/admin/elections'); elections.value = result.elections; electionId.value = elections.value[0]?.id ?? ''; if (electionId.value) await loadActions() } catch (e) { error.value = apiErrorMessage(e) } }
async function loadActions() { if (!electionId.value) return; loading.value = true; try { actions.value = (await $fetch<{ actions: Action[] }>(`/api/v1/admin/elections/${encodeURIComponent(electionId.value)}/actions`, { retry: 0 })).actions } catch (e) { error.value = apiErrorMessage(e) } finally { loading.value = false } }
async function propose(kind: string) { saving.value = true; error.value = ''; notice.value = ''; try { const result = await request<{ requiresApproval: boolean }>(`/api/v1/admin/elections/${encodeURIComponent(electionId.value)}/actions`, { kind }); notice.value = result.requiresApproval ? 'Usulan dikirim dan menunggu persetujuan petugas lain.' : 'Voting berhasil dibuka.'; await Promise.all([loadElections(), loadActions()]) } catch (e) { error.value = apiErrorMessage(e) } finally { saving.value = false } }
async function pause() { if (pauseReason.value.trim().length < 3) { error.value = 'Alasan jeda wajib diisi minimal 3 karakter.'; return } saving.value = true; error.value = ''; try { await request(`/api/v1/admin/elections/${encodeURIComponent(electionId.value)}/actions`, { kind: 'PAUSE', reason: pauseReason.value.trim() }); pauseReason.value = ''; notice.value = 'Voting dijeda.'; await Promise.all([loadElections(), loadActions()]) } catch (e) { error.value = apiErrorMessage(e) } finally { saving.value = false } }
async function decide(id: string, decision: 'approve' | 'reject') { saving.value = true; error.value = ''; try { await request(`/api/v1/admin/actions/${encodeURIComponent(id)}/${decision}`, {}); notice.value = decision === 'approve' ? 'Usulan disetujui.' : 'Usulan ditolak.'; await Promise.all([loadElections(), loadActions()]) } catch (e) { error.value = apiErrorMessage(e) } finally { saving.value = false } }
watch(electionId, () => { if (electionId.value) void loadActions() }); onMounted(loadElections)
</script>
<template>
  <section class="operations"><header class="page-header"><div><p class="eyebrow">OPERASIONAL</p><h1>Kontrol periode</h1><p class="intro">Buka, jeda, dan tutup voting dengan jejak persetujuan yang jelas.</p></div><label class="period-select">Periode<select v-model="electionId"><option v-for="e in elections" :key="e.id" :value="e.id">{{ e.name }} · {{ e.status }}</option></select></label></header><AppAlert v-if="error" kind="error" :message="error"/><AppAlert v-if="notice" kind="success" :message="notice"/><section v-if="current" class="status-panel"><div><span class="status-label">Status saat ini</span><strong>{{ current.status }}</strong><p v-if="current.startsAt">Jadwal {{ new Date(current.startsAt).toLocaleString('id-ID') }} – {{ current.endsAt ? new Date(current.endsAt).toLocaleString('id-ID') : 'belum ditentukan' }}</p></div><div class="controls"><AppButton v-if="current.status === 'READY'" :loading="saving" @click="propose('OPEN')">Buka voting</AppButton><AppButton v-if="current.status === 'PAUSED'" variant="secondary" :loading="saving" @click="propose('RECOVER')">Lanjutkan voting</AppButton><AppButton v-if="['OPEN','PAUSED'].includes(current.status)" variant="secondary" :loading="saving" @click="propose('CLOSE_EARLY')">Tutup lebih awal</AppButton><AppButton v-if="current.status === 'CLOSED'" :loading="saving" @click="propose('PUBLISH')">Ajukan publikasi</AppButton></div></section><div v-if="current?.status === 'OPEN'" class="pause-form"><AppInput v-model="pauseReason" label="Alasan jeda voting" hint="Wajib diisi bila terjadi insiden."/><AppButton variant="danger" :loading="saving" @click="pause">Jeda dengan alasan</AppButton></div><section class="actions-section"><div class="section-heading"><h2>Usulan tindakan</h2><span>{{ actions.length }} terakhir</span></div><div v-if="loading" role="status" class="state">Memuat usulan…</div><div v-else-if="!actions.length" class="state">Belum ada usulan tindakan.</div><div v-else class="action-list"><article v-for="action in actions" :key="action.id" class="action-row"><div><strong>{{ labels[action.type] ?? action.type }}</strong><span>{{ action.status }} · {{ new Date(action.createdAt).toLocaleString('id-ID') }}</span></div><div v-if="action.status === 'PENDING'" class="action-buttons"><AppButton variant="secondary" :loading="saving" @click="decide(action.id, 'approve')">Setujui</AppButton><AppButton variant="ghost" :loading="saving" @click="decide(action.id, 'reject')">Tolak</AppButton></div></article></div></section></section>
</template>
<style scoped>
.operations{display:grid;gap:var(--space-6)}.page-header{display:flex;justify-content:space-between;align-items:end;gap:var(--space-6);flex-wrap:wrap}.eyebrow{margin:0 0 var(--space-2);color:var(--color-primary);font-size:.75rem;font-weight:700;letter-spacing:.08em}.page-header h1{margin-bottom:var(--space-2)}.intro,.status-panel p,.section-heading span,.action-row span{margin:0;color:var(--color-text-muted)}.period-select{display:grid;gap:var(--space-1);font-size:var(--text-sm);font-weight:600}.period-select select{min-width:18rem;min-height:2.75rem;padding:var(--space-2) var(--space-3);border:1px solid var(--color-border-strong);border-radius:var(--radius);background:var(--color-surface);font:inherit}.status-panel,.pause-form{display:flex;justify-content:space-between;align-items:center;gap:var(--space-6);padding:var(--card-padding);background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-xl);box-shadow:var(--shadow-sm)}.status-label{display:block;font-size:var(--text-sm);color:var(--color-text-muted)}.status-panel strong{display:block;font-size:var(--text-2xl);color:var(--color-primary-strong)}.controls,.action-buttons{display:flex;gap:var(--space-3);flex-wrap:wrap}.pause-form{align-items:end}.pause-form .field{flex:1}.actions-section{display:grid;gap:var(--space-4)}.section-heading{display:flex;align-items:baseline;gap:var(--space-3)}.section-heading h2{margin:0;font-size:var(--text-lg)}.action-list{display:grid;gap:var(--space-3)}.action-row{display:flex;justify-content:space-between;align-items:center;gap:var(--space-4);padding:var(--card-padding);background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-lg)}.action-row strong,.action-row span{display:block}.action-row span{font-size:var(--text-sm)}.state{padding:var(--space-8) var(--space-4);text-align:center;color:var(--color-text-muted);background:var(--color-surface);border:1px dashed var(--color-border-strong);border-radius:var(--radius-lg)}
@media(max-width:42rem){.period-select,.period-select select{width:100%;min-width:0}.status-panel,.pause-form,.action-row{align-items:stretch;flex-direction:column}.controls,.controls>* ,.action-buttons,.action-buttons>*{width:100%}}
</style>
