<script setup lang="ts">
type Election = { id: string; name: string; status: string }
type Contest = { id: string; code: string; title: string }
type Voter = { id: string; name: string; identifierValue: string; voterType: string; departmentCode: string | null; rights: string[] }
type Matrix = { configVersion: number; contests: Contest[]; voters: Voter[]; total: number; page: number; pageSize: number }
const { request } = useApi(); const elections = ref<Election[]>([]); const electionId = ref(''); const matrix = ref<Matrix | null>(null); const search = ref(''); const voterType = ref(''); const departmentCode = ref(''); const page = ref(1); const pageSize = 30; const loading = ref(false); const saving = ref(false); const error = ref(''); const notice = ref(''); const reason = ref('')
const changes = reactive<Record<string, boolean>>({})
const departments = ['KEP', 'KEB', 'KG', 'OP']
const changeList = computed(() => Object.entries(changes).map(([key, grant]) => { const [voterId, contestId] = key.split(':'); return { voterId, contestId, grant } }))
function path() { const q = new URLSearchParams({ page: String(page.value), pageSize: String(pageSize) }); if (search.value) q.set('search', search.value); if (voterType.value) q.set('voterType', voterType.value); if (departmentCode.value) q.set('departmentCode', departmentCode.value); return `/api/v1/admin/elections/${encodeURIComponent(electionId.value)}/rights-matrix?${q}` }
async function loadElections() { try { const result = await request<{ elections: Election[] }>('/api/v1/admin/elections'); elections.value = result.elections.filter(e => ['DRAFT', 'READY'].includes(e.status)); electionId.value = elections.value[0]?.id ?? ''; if (electionId.value) await loadMatrix() } catch (e) { error.value = apiErrorMessage(e) } }
async function loadMatrix() { if (!electionId.value) return; loading.value = true; error.value = ''; try { matrix.value = await $fetch<Matrix>(path(), { retry: 0, timeout: 15_000 }); Object.keys(changes).forEach(key => delete changes[key]) } catch (e) { error.value = apiErrorMessage(e) } finally { loading.value = false } }
function toggle(voter: Voter, contest: Contest) { const key = `${voter.id}:${contest.id}`; const current = voter.rights.includes(contest.id); const next = !current; if (next === current) delete changes[key]; else changes[key] = next }
async function saveChanges() { if (!matrix.value || !changeList.value.length || reason.value.trim().length < 3) { error.value = 'Pilih perubahan dan isi alasan minimal 3 karakter.'; return } saving.value = true; error.value = ''; notice.value = ''; try { const result = await request<{ applied: number; reverted: number }>(`/api/v1/admin/elections/${encodeURIComponent(electionId.value)}/rights`, { electionId: electionId.value, expectConfigVersion: matrix.value.configVersion, changes: changeList.value, reason: reason.value.trim() }); notice.value = `${result.applied} perubahan hak diterapkan.`; reason.value = ''; await loadMatrix() } catch (e) { error.value = apiErrorMessage(e) } finally { saving.value = false } }
watch([electionId, search, voterType, departmentCode], () => { page.value = 1; if (electionId.value) void loadMatrix() }); watch(page, () => { if (electionId.value) void loadMatrix() }); onMounted(loadElections)
</script>
<template>
  <section class="matrix-page"><header class="page-header"><div><p class="eyebrow">PENYESUAIAN HAK</p><h1>Hak per pemilih</h1><p class="intro">Centang kontes yang boleh dipilih. Perubahan dicatat bersama alasan.</p></div><NuxtLink class="action-link" to="/admin/rights">Kembali ke kesiapan</NuxtLink></header><AppAlert v-if="error" kind="error" :message="error"/><AppAlert v-if="notice" kind="success" :message="notice"/><div class="filters"><label>Periode<select v-model="electionId"><option v-for="e in elections" :key="e.id" :value="e.id">{{ e.name }}</option></select></label><AppInput v-model="search" label="Cari pemilih" type="search"/><label>Jenis<select v-model="voterType"><option value="">Semua</option><option value="STUDENT">Mahasiswa</option><option value="LECTURER">Dosen</option></select></label><label>Jurusan<select v-model="departmentCode"><option value="">Semua</option><option v-for="d in departments" :key="d" :value="d">{{ d }}</option></select></label></div><div v-if="loading" class="state" role="status">Memuat matriks…</div><template v-else-if="matrix"><div class="matrix-wrap" role="region" aria-label="Matriks hak pilih" tabindex="0"><table><thead><tr><th>Pemilih</th><th v-for="contest in matrix.contests" :key="contest.id" :title="contest.title">{{ contest.code }}</th></tr></thead><tbody><tr v-for="voter in matrix.voters" :key="voter.id"><th scope="row"><span>{{ voter.name }}</span><small>{{ voter.identifierValue }} · {{ voter.departmentCode ?? '—' }}</small></th><td v-for="contest in matrix.contests" :key="contest.id"><input type="checkbox" :checked="changes[`${voter.id}:${contest.id}`] ?? voter.rights.includes(contest.id)" :aria-label="`${contest.code} untuk ${voter.name}`" @change="toggle(voter, contest)"></td></tr></tbody></table></div><AppPagination v-model:page="page" :page-size="pageSize" :total="matrix.total"/><section class="save-bar"><div><strong>{{ changeList.length }} perubahan belum disimpan</strong><p>Gunakan alasan yang dapat diperiksa panitia lain.</p></div><div class="save-controls"><input v-model="reason" aria-label="Alasan perubahan" placeholder="Alasan perubahan…" maxlength="500"><AppButton :loading="saving" :disabled="!changeList.length" @click="saveChanges">Simpan perubahan</AppButton></div></section></template><div v-else class="state">Belum ada periode DRAFT atau READY.</div></section>
</template>
<style scoped>
.matrix-page{display:grid;gap:var(--space-6)}.page-header{display:flex;justify-content:space-between;align-items:end;gap:var(--space-6);flex-wrap:wrap}.eyebrow{margin:0 0 var(--space-2);color:var(--color-primary);font-size:.75rem;font-weight:700;letter-spacing:.08em}.page-header h1{margin-bottom:var(--space-2)}.intro,.save-bar p{margin:0;color:var(--color-text-muted)}.filters{display:grid;grid-template-columns:1.5fr 2fr 1fr 1fr;gap:var(--space-4);padding:var(--space-4);background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-lg)}.filters label{display:grid;gap:var(--space-1);font-size:var(--text-sm);font-weight:600}.filters select,.save-controls input{min-height:2.75rem;padding:var(--space-2) var(--space-3);border:1px solid var(--color-text-muted);border-radius:var(--radius);background:var(--color-surface);font:inherit}.matrix-wrap{overflow:auto;border:1px solid var(--color-border);border-radius:var(--radius)}table{width:100%;min-width:54rem;border-collapse:collapse;background:var(--color-surface);font-size:var(--text-sm)}th,td{padding:var(--space-3);border-bottom:1px solid var(--color-border);text-align:center}thead th{background:var(--color-primary-soft);position:sticky;top:0;z-index:1}tbody th{text-align:start;min-width:15rem}tbody th span,tbody th small{display:block}tbody th small{color:var(--color-text-muted);font-weight:400}td input{width:1.25rem;height:1.25rem;accent-color:var(--color-primary)}.state{padding:var(--space-8) var(--space-4);text-align:center;color:var(--color-text-muted);background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius)}.save-bar{display:flex;justify-content:space-between;align-items:center;gap:var(--space-4);padding:var(--space-4);background:var(--color-primary-soft);border:1px solid var(--color-primary);border-radius:var(--radius-lg)}.save-controls{display:flex;gap:var(--space-3);align-items:center}.save-controls input{min-width:18rem}.filters select:focus-visible,.save-controls input:focus-visible,td input:focus-visible{outline:none;box-shadow:var(--focus-ring)}
@media(max-width:48rem){.filters{grid-template-columns:1fr 1fr}.filters :deep(.field):first-child{grid-column:1/-1}.save-bar,.save-controls{align-items:stretch;flex-direction:column}.save-controls input,.save-controls button{width:100%}}
@media(max-width:30rem){.filters{grid-template-columns:1fr}}
</style>
